# Copyright (C) Contrasec 2022
#.gitlab-ci.yml

# Deployment script

.deploy_template: &deploy_template
  tags:
    - kubernetes #Only runners with this tag are used
  image: bitnami/kubectl:latest
  stage: deploy
  script:
    - echo "$KUBE" > config  # Echo Kubeconfig to a file
                             # so it can be used by kubectl
    # Create secret for mysql (root password)
    - kubectl create secret generic mysql-secret --from-literal=password=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-20} | head -n 1 | sed 's/ *$//g') -n ${NAMESPACE} --kubeconfig config || true
    # Apply file into kubernetes with kubectl
    - kubectl apply -f resource.yaml --namespace ${NAMESPACE} --kubeconfig config

# Stages
  
stages:
  - deploy


# Staging deployment stage

do deploy staging:
  <<: *deploy_template
  variables:
    NAMESPACE: odala-staging
    KUBE: $KUBECONFIG                 # Get KUBECONFIG from Gitlab CI/CD variable
  only:
    #- /^C./                           # Every branch that starts with C #################################################
    - /^odala-staging./              # Only odala-staging              #################################################
    

# Production deployment stage

do deploy prod:
  <<: *deploy_template
  variables:
    NAMESPACE: odala-production
    KUBE: $KUBECONFIG                 # Get KUBECONFIG from Gitlab CI/CD variable
  only:
    #- /^R./                           # Every branch that starts with R #################################################
    - odala-production               # Only odala-production           #################################################
  when: manual                        # Require manual step in pipeline to deploy to prod. Remove if not needed
